# Generated by Django 3.1.7 on 2021-03-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_auto_20210308_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Mis departamentos', 'verbose_name_plural': 'Areas de la empresa'},
        ),
    ]
