# Generated by Django 3.1.7 on 2021-03-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='subtititulo',
            new_name='subtitulo',
        ),
    ]
